/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-19 at 22:27:59 UTC 
 * Modify at your own risk.
 */

package com.appspot.ideas_staging.ideasapi.model;

/**
 * ProtoRPC container for users.User objects. Attributes: email: String; The email of the user.
 * auth_domain: String; The auth domain of the user. user_id: String; The user ID.
 * federated_identity: String; The federated identity of the user.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the ideasapi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("auth_domain")
  private java.lang.String authDomain;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("federated_identity")
  private java.lang.String federatedIdentity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_id")
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthDomain() {
    return authDomain;
  }

  /**
   * @param authDomain authDomain or {@code null} for none
   */
  public UserMessage setAuthDomain(java.lang.String authDomain) {
    this.authDomain = authDomain;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public UserMessage setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFederatedIdentity() {
    return federatedIdentity;
  }

  /**
   * @param federatedIdentity federatedIdentity or {@code null} for none
   */
  public UserMessage setFederatedIdentity(java.lang.String federatedIdentity) {
    this.federatedIdentity = federatedIdentity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public UserMessage setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public UserMessage set(String fieldName, Object value) {
    return (UserMessage) super.set(fieldName, value);
  }

  @Override
  public UserMessage clone() {
    return (UserMessage) super.clone();
  }

}
